#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=dnsdist DNS Forwarder Configuration
LUCI_DEPENDS:=+luci-compat +dnsdist

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
